const { createProperty } = require('../controllers/createProperty')

const createPropertyHandler = async (req, res) => {
    try {
        const {
            propertyType,
            photo,
            videoLink,
            status,
            currency,
            price,
            currencyExpenses,
            expenses,
            totalSquareMeters,
            coveredSquareMeters,
            semiCoveredSquareMeters,
            uncovered,
            land,
            age,
            commissionSellerType,
            commissionBuyerType,
            sellerCommission,
            buyerCommission,
            availableDate,
            expirationDate,
            location,
            street,
            number,
            country,
            province,
            departments,
            locality,
            neighborhood,
            privateNeighborhood,
            propertyState,
            environments,
            rooms,
            bathrooms,
            toilettes,
            garages,
            amenitiesOptions,
            servicesOptions,
            title,
            description,
            floorPlans,
            documentation,
            sellerId,
            userId,
            exclusiveContract,
            cartel,
            financing,
            suitableCredit,
            commercialSuitable,
            professionalSuitable,
            suitableForReducedMobility,
            pozo,
            CountryOrPrivateNeighborhood,
        } = req.body;

        const newProperty = await createProperty({
            propertyType,
            photo,
            videoLink,
            status,
            currency,
            price,
            currencyExpenses,
            expenses,
            totalSquareMeters,
            coveredSquareMeters,
            semiCoveredSquareMeters,
            uncovered,
            land,
            age,
            commissionSellerType,
            commissionBuyerType,
            sellerCommission,
            buyerCommission,
            availableDate,
            expirationDate,
            location,
            street,
            number,
            country,
            province,
            departments,
            locality,
            neighborhood,
            privateNeighborhood,
            propertyState,
            environments,
            rooms,
            bathrooms,
            toilettes,
            garages,
            amenitiesOptions,
            servicesOptions,
            title,
            description,
            floorPlans,
            documentation,
            sellerId,
            userId,
            exclusiveContract,
            cartel,
            financing,
            suitableCredit,
            commercialSuitable,
            professionalSuitable,
            suitableForReducedMobility,
            pozo,
            CountryOrPrivateNeighborhood,       
        });

        res.status(201).json({
            success: true,
            message: 'Propiedad creada exitosamente',
            data: newProperty,
        });
    } catch (error) {
        console.error('Error al crear la propiedad:', error.message);
        res.status(500).json({
            success: false,
            message: 'Error al crear la propiedad',
        });
    }
};

module.exports = {
    createPropertyHandler
};